services:
  app:
    container_name: java-auth
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgres
    ports:
      - '8080:8080'
  postgres:
    container_name: auth-supabase
    image: 'postgres:17.2'
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  postgres_data: